### ISSUE TITLE
Uniform real dimension interval does not align with input

### ISSUE THREAD

**Issue by donglinjy** [Epistimio/orion#1018]
Try different inputs as below. The first one is how we map `Configspace UniformFloatHyperparameter` into orion `Real` dimension.

```
>>> from orion.algo.space import Real,Dimension
>>> 
>>> Real("final_lr_fraction_log2", "uniform", -4.0, 0.0, default_value=-0.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 462, in __init__
    super().__init__(name, prior, *args, **kwargs)
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 185, in __init__
    self.validate()
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 206, in validate
    raise ValueError(
ValueError: -0.2 is not a valid value for this Dimension. Can't set default value.
>>> 
>>> Real("final_lr_fraction_log2", "uniform", -4.0, 0.0, low=-4.0, high=0.0, default_value=-0.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 462, in __init__
    super().__init__(name, prior, *args, **kwargs)
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 185, in __init__
    self.validate()
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 206, in validate
    raise ValueError(
ValueError: -0.2 is not a valid value for this Dimension. Can't set default value.
>>> 
>>> Real("final_lr_fraction_log2", "uniform", low=-4.0, high=0.0, default_value=-0.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 462, in __init__
    super().__init__(name, prior, *args, **kwargs)
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 185, in __init__
    self.validate()
  File "/root/donglbj/hpobench/orion/src/orion/algo/space/__init__.py", line 206, in validate
    raise ValueError(
ValueError: -0.2 is not a valid value for this Dimension. Can't set default value.
```

@bouthilx

**Comment by Delaunay** [comment]
So the behavior with `Real` is expected this is because the uniform dimension does not take
 `min, max` as parameters but `min, scale` with `scale = max - min`.
 
 The conversion is done inside by the dimension builder which is generally used to create the Orion Space.
 There is a bug in the Orion space => Config Space function which was not making the right conversion.
 PR#1034 should fix this
 
 Thank you
