### ISSUE TITLE
PB2 key error 

### ISSUE THREAD

**Issue by Delaunay** [Epistimio/orion#1021]
```
Traceback (most recent call last):
  File "/home/newton/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/newton/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/home/newton/miniconda3/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/newton/work/hydra_orion_sweeper/hydra_plugins/hydra_orion_sweeper/orion_sweeper.py", line 64, in sweep
    return self.sweeper.sweep(arguments)
  File "/home/newton/work/hydra_orion_sweeper/hydra_plugins/hydra_orion_sweeper/implementation.py", line 476, in sweep
    raise e
  File "/home/newton/work/hydra_orion_sweeper/hydra_plugins/hydra_orion_sweeper/implementation.py", line 473, in sweep
    self.optimize(self.client)
  File "/home/newton/work/hydra_orion_sweeper/hydra_plugins/hydra_orion_sweeper/implementation.py", line 491, in optimize
    trials = self.sample_trials()
  File "/home/newton/work/hydra_orion_sweeper/hydra_plugins/hydra_orion_sweeper/implementation.py", line 521, in sample_trials
    trials = self.suggest_trials(self.n_workers())
  File "/home/newton/work/hydra_orion_sweeper/hydra_plugins/hydra_orion_sweeper/implementation.py", line 400, in suggest_trials
    trial = self.client.suggest(pool_size=count)
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/client/experiment.py", line 562, in suggest
    trial = reserve_trial(
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/client/experiment.py", line 55, in reserve_trial
    produced = producer.produce(pool_size)
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/core/worker/producer.py", line 48, in produce
    new_trials = algorithm.suggest(pool_size)
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/core/worker/primary_algo.py", line 144, in suggest
    transformed_trials: list[Trial] | None = self.algorithm.suggest(num)
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/algo/pbt/pbt.py", line 345, in suggest
    forked_trials = self._fork_lineages(num_fork_samples)
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/algo/pbt/pbt.py", line 395, in _fork_lineages
    trial_to_branch, new_trial = self._generate_offspring(trial)
  File "/home/newton/miniconda3/lib/python3.9/site-packages/orion/algo/pbt/pb2.py", line 170, in _generate_offspring
    new_params[self.fidelity_index] = self.fidelity_upgrades[
KeyError: 10
```

**Comment by Delaunay** [comment]
```
    params:
      optimizer:
        name: "choices(['Adam', 'SGD'])"
        lr: "uniform(0, 1)"
      dropout: "uniform(0, 1)"
      batch_size: "uniform(4, 16, discrete=True)"
      epoch: "fidelity(10, 100)"
```
