### ISSUE TITLE
Unable to pip install Orion on Python 3.12

### ISSUE THREAD

**Issue by lebrice** [Epistimio/orion#1127]
**Describe the bug**
Can't install Orion with pip from python 3.12:
```
$ conda create -n temp python=3.12
$ conda activate temp
$ pip install orion
Collecting orion
  Using cached orion-0.2.7.tar.gz (29.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wd3nblnz/orion_99b19ebc2b92461ab6137d80528cc0e4/setup.py", line 95, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-wd3nblnz/orion_99b19ebc2b92461ab6137d80528cc0e4/versioneer.py", line 1523, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-wd3nblnz/orion_99b19ebc2b92461ab6137d80528cc0e4/versioneer.py", line 1450, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-wd3nblnz/orion_99b19ebc2b92461ab6137d80528cc0e4/versioneer.py", line 345, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```
```

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.12
 - Oríon version: 0.2.7

**Additional context**
If applicable, attach any log of screenshots that can help explain the problem.

** Possible solution**
If you think you know what the problem is, let us know! Your opinion helps us.

**Comment by lebrice** [comment]
I still have the same issue with this btw!

**Comment by lebrice** [comment]
Same as https://github.com/warner/python-spake2/issues/13

**Comment by leademeule** [comment]
Also experiencing this on Python 3.12.10. Is there any relatively straightforward workaround at the time?
