### ISSUE TITLE
AttributeError: Cannot access attribute node on view-only experiments.

### ISSUE THREAD

**Issue by christopher-beckham** [Epistimio/orion#143]
Following the Orion tutorial here:

https://github.com/bouthilx/orion.tutorial
(tested this both on the latest master commit `fc4aa14dd58bf50196aa6ad3a2869e3d86ca1a45` and the version from pip suggested in the tutorial)

If I run the code in the section explaining how to retrieve results from the EVC:

```
import pprint
from orion.core.io.evc_builder import EVCBuilder

experiment = EVCBuilder().build_view_from(
    {"name": "orion-tutorial-with-momentum"})

print(experiment.name)
pprint.pprint(experiment.stats)

##

parent_experiment = experiment.node.parent.item
print(parent_experiment.name)
pprint.pprint(parent_experiment.stats)

for child in experiment.node.children:
    child_experiment = child.item
    print(child_experiment.name)
    pprint.pprint(child_experiment.stats)
```

I get this error:

```
Traceback (most recent call last):
  File "see_results_2.py", line 13, in <module>
    parent_experiment = experiment.node.parent.item
  File "/u/beckhamc/.conda/envs/orion.tutorial/lib/python3.6/site-packages/orion/core/worker/experiment.py", line 651, in __getattr__
    raise AttributeError("Cannot access attribute %s on view-only experiments." % name)
AttributeError: Cannot access attribute node on view-only experiments.
```

As Xavier suggested, my current workaround is to do:

```
parent_experiment = experiment._experiment._node.parent.item
print(parent_experiment.name)
pprint.pprint(parent_experiment.stats)

for child in experiment._experiment._node.children:
    child_experiment = child.item
    print(child_experiment.name)
    pprint.pprint(child_experiment.stats)
```

**Comment by bouthilx** [comment]
Thanks for opening the issue! I got confused with Kleio, which has a ```node``` attribute in its version control system, but Orion does not have it yet. That would be a rather simple contribution, you can make a pull request adding property node to experiment ([like here](https://github.com/Epistimio/orion/blob/master/src/orion/core/worker/experiment.py#L301-L307)) and add it to the white-list of [ExperientView](https://github.com/Epistimio/orion/blob/master/src/orion/core/worker/experiment.py#L610). Otherwise I'll try to take care of it soon.

**Comment by christopher-beckham** [comment]
I'm stuck at figuring out a reasonable docstring for the node property :) Probably be faster for you to add it in than me, if you want!

**Comment by bouthilx** [comment]
Faster for me to add the entire thing or the docstring specifically? If you want to contribute a PR I don't mind contributing to it. :)

**Comment by DatCorno** [comment]
Has the issue been solved?

**Comment by bouthilx** [comment]
Yes thanks pointing it out!
