### ISSUE TITLE
Bad resuming with pickle DB

### ISSUE THREAD

**Issue by Delaunay** [Epistimio/orion#320]
```
Traceback (most recent call last):
  File "olympus/baselines/launch.py", line 276, in <module>
    main()
  File "olympus/baselines/launch.py", line 254, in main
    single_worker_single_gpu(args.task, script_args, args.no_mon)
  File "olympus/baselines/launch.py", line 183, in single_worker_single_gpu
    simple_launch(task, args)
  File "olympus/baselines/launch.py", line 92, in simple_launch
    module.main(**vars(args))
  File "/home/setepenre/work/olympus/olympus/baselines/a2c.py", line 160, in main
    hpo.fit(epochs=fidelity(args.epochs), objective='loss')
  File "/home/setepenre/work/olympus/olympus/tasks/hpo.py", line 120, in fit
    for idx, trial in enumerate(iterator):
  File "/home/setepenre/work/olympus/olympus/hpo/__init__.py", line 37, in __next__
    trial = self.experiment.suggest()
  File "/home/setepenre/work/orion/src/orion/client/experiment.py", line 391, in suggest
    trial = orion.core.worker.reserve_trial(self._experiment, self._producer)
  File "/home/setepenre/work/orion/src/orion/core/worker/__init__.py", line 32, in reserve_trial
    producer.update()
  File "/home/setepenre/work/orion/src/orion/core/worker/producer.py", line 109, in update
    self._update_algorithm([trial for trial in trials if trial.status == 'completed'])
  File "/home/setepenre/work/orion/src/orion/core/worker/producer.py", line 131, in _update_algorithm
    self.algorithm.observe(points, results)
  File "/home/setepenre/work/orion/src/orion/core/worker/primary_algo.py", line 94, in observe
    self.algorithm.observe(tpoints, results)
  File "/home/setepenre/work/orion/src/orion/algo/asha.py", line 248, in observe
    "No bracket found for point {0} with fidelity {1}".format(_id, fidelity))
ValueError: No bracket found for point f2e6bc2cbd07db0dba953d18152697ec with fidelity 2
```

**Comment by Thomsch** [comment]
This error didn't reappear. I'm closing this for now.
