### ISSUE TITLE
Using parameters with a "." in their name causes a crash

### ISSUE THREAD

**Issue by lebrice** [Epistimio/orion#769]
See title.

Python 3.8
Orion v0.2.1

```console
orion hunt -n my_exp python main.py --b_optim.lr~'loguniform(1e-6, 0.5, shape=4)' --debug
Traceback (most recent call last):
  File "/home/fabrice/miniconda3/envs/target_prop/bin/orion", line 8, in <module>
    sys.exit(main())
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/cli/__init__.py", line 37, in main
    return orion_parser.execute(argv)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/cli/base.py", line 89, in execute
    returncode = function(args)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/cli/hunt.py", line 198, in main
    experiment = experiment_builder.build_from_args(args)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 752, in build_from_args
    return build(**cmd_config)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 175, in build
    config = consolidate_config(name, version, config)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 264, in consolidate_config
    resolve_config.update_metadata(config["metadata"])
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/resolve_config.py", line 303, in update_metadata
    cmdline_parser.set_state_dict(metadata["parser"])
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/orion_cmdline_parser.py", line 134, in set_state_dict
    self.infer_user_script(self.parser.format(self.parser.arguments))
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/cmdline_parser.py", line 98, in format
    formatted.append(item.format(**configuration))
KeyError: 'b_optim'
```

**Comment by lebrice** [comment]
More info:
```python
# orion_bug.py:
import argparse


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--b_optim.lr", type=float, nargs="*", default=[1e-3], help="learning rate of b_optim"
    )

    args = parser.parse_args()
    args_dict = vars(args)
    optim_lr = args_dict["b_optim.lr"]
    print(f"Optim lr: {optim_lr}")


if __name__ == "__main__":
    main()
```


Output:


```console
$ orion -vvv hunt -n bug python sweep_configs/orion_bug.py --b_optim.lr~'loguniform(1e-6, 0.5, shape=4)' 
2022-01-25 15:19:45,224::DEBUG::git.cmd::Popen(['git', 'cat-file', '--batch-check'], cwd=/home/fabrice/repos/scalingDTP, universal_newlines=False, shell=None, istream=<valid stream>)
2022-01-25 15:19:45,235::DEBUG::git.cmd::Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/home/fabrice/repos/scalingDTP, universal_newlines=False, shell=None, istream=None)
2022-01-25 15:19:45,247::DEBUG::git.cmd::Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/home/fabrice/repos/scalingDTP, universal_newlines=False, shell=None, istream=None)
2022-01-25 15:19:45,263::DEBUG::git.cmd::Popen(['git', 'cat-file', '--batch'], cwd=/home/fabrice/repos/scalingDTP, universal_newlines=False, shell=None, istream=<valid stream>)
2022-01-25 15:19:45,274::DEBUG::git.cmd::Popen(['git', 'diff', '895c2612efa65ce301b00c0ca91b1588d799f3e3'], cwd=/home/fabrice/repos/scalingDTP, universal_newlines=False, shell=None, istream=None)
2022-01-25 15:19:45,292::DEBUG::orion.storage.base::Creating legacy storage client with args: {'database': {'name': 'orion', 'type': 'ephemeraldb', 'host': '', 'port': 27017}}
2022-01-25 15:19:45,390::DEBUG::orion.core.utils::Found a legacy BaseStorageProtocol from distribution: orion=0.2.1
2022-01-25 15:19:45,392::DEBUG::orion.core.utils::Found a track BaseStorageProtocol from distribution: orion=0.2.1
2022-01-25 15:19:45,429::DEBUG::orion.storage.legacy::Creating ephemeraldb database client with args: {'name': 'orion', 'host': '', 'port': 27017}
2022-01-25 15:19:45,431::DEBUG::orion.core.utils::Found a ephemeraldb Database from distribution: orion=0.2.1
2022-01-25 15:19:45,433::DEBUG::orion.core.utils::Found a mongodb Database from distribution: orion=0.2.1
2022-01-25 15:19:45,434::DEBUG::orion.core.utils::Found a pickleddb Database from distribution: orion=0.2.1
2022-01-25 15:19:45,434::DEBUG::orion.core.io.experiment_builder::Building experiment bug with None
2022-01-25 15:19:45,435::DEBUG::orion.core.io.experiment_builder::    Passed experiment config:
{'debug': False,
 'metadata': {'VCS': {'HEAD_sha': 'e987e9272235cea57b8121412d0d25ae24075898',
                      'active_branch': 'numerical_experiments',
                      'diff_sha': '1e41bd0f60270609869157525ba045663ef27f7d7cedf30342b8322ff3d8225c',
                      'is_dirty': True,
                      'type': 'git'},
              'orion_version': '0.2.1',
              'parser': {'cmd_priors': [['/b_optim.lr',
                                         'loguniform(1e-6, 0.5, shape=4)']],
                         'config_file_data': {},
                         'config_prefix': 'config',
                         'converter': None,
                         'file_config_path': None,
                         'file_priors': [],
                         'parser': {'arguments': [['_pos_0', 'python'],
                                                  ['_pos_1',
                                                   '/home/fabrice/repos/scalingDTP/sweep_configs/orion_bug.py'],
                                                  ['b_optim.lr',
                                                   'orion~loguniform(1e-6, '
                                                   '0.5, shape=4)']],
                                    'keys': [['_pos_0', '_pos_0'],
                                             ['_pos_1', '_pos_1'],
                                             ['b_optim.lr', '--b_optim.lr']],
                                    'template': ['{_pos_0}',
                                                 '{_pos_1}',
                                                 '--b_optim.lr',
                                                 '{b_optim.lr}']}},
              'priors': {'/b_optim.lr': 'loguniform(1e-6, 0.5, shape=4)'},
              'user': 'fabrice',
              'user_args': ['python',
                            'sweep_configs/orion_bug.py',
                            '--b_optim.lr~loguniform(1e-6, 0.5, shape=4)'],
              'user_script': 'sweep_configs/orion_bug.py',
              'user_script_config': 'config'},
 'space': {'/b_optim.lr': 'loguniform(1e-6, 0.5, shape=4)'},
 'storage': {'database': {'host': '',
                          'name': 'orion',
                          'port': 27017,
                          'type': 'ephemeraldb'},
             'type': 'legacy'},
 'user_args': ['python',
               'sweep_configs/orion_bug.py',
               '--b_optim.lr~loguniform(1e-6, 0.5, shape=4)'],
 'user_script_config': None}
2022-01-25 15:19:45,435::DEBUG::orion.core.io.experiment_builder::    Branching config:
{}
2022-01-25 15:19:45,435::DEBUG::orion.core.io.experiment_builder::Cleaning config
2022-01-25 15:19:45,435::DEBUG::orion.core.io.experiment_builder::Ignoring field user_script_config
2022-01-25 15:19:45,435::DEBUG::orion.core.io.experiment_builder::Cleaned experiment config
2022-01-25 15:19:45,436::DEBUG::orion.core.io.experiment_builder::    Experiment config:
{'debug': False,
 'metadata': {'VCS': {'HEAD_sha': 'e987e9272235cea57b8121412d0d25ae24075898',
                      'active_branch': 'numerical_experiments',
                      'diff_sha': '1e41bd0f60270609869157525ba045663ef27f7d7cedf30342b8322ff3d8225c',
                      'is_dirty': True,
                      'type': 'git'},
              'orion_version': '0.2.1',
              'parser': {'cmd_priors': [['/b_optim.lr',
                                         'loguniform(1e-6, 0.5, shape=4)']],
                         'config_file_data': {},
                         'config_prefix': 'config',
                         'converter': None,
                         'file_config_path': None,
                         'file_priors': [],
                         'parser': {'arguments': [['_pos_0', 'python'],
                                                  ['_pos_1',
                                                   '/home/fabrice/repos/scalingDTP/sweep_configs/orion_bug.py'],
                                                  ['b_optim.lr',
                                                   'orion~loguniform(1e-6, '
                                                   '0.5, shape=4)']],
                                    'keys': [['_pos_0', '_pos_0'],
                                             ['_pos_1', '_pos_1'],
                                             ['b_optim.lr', '--b_optim.lr']],
                                    'template': ['{_pos_0}',
                                                 '{_pos_1}',
                                                 '--b_optim.lr',
                                                 '{b_optim.lr}']}},
              'priors': {'/b_optim.lr': 'loguniform(1e-6, 0.5, shape=4)'},
              'user': 'fabrice',
              'user_args': ['python',
                            'sweep_configs/orion_bug.py',
                            '--b_optim.lr~loguniform(1e-6, 0.5, shape=4)'],
              'user_script': 'sweep_configs/orion_bug.py',
              'user_script_config': 'config'},
 'space': {'/b_optim.lr': 'loguniform(1e-6, 0.5, shape=4)'},
 'storage': {'database': {'host': '',
                          'name': 'orion',
                          'port': 27017,
                          'type': 'ephemeraldb'},
             'type': 'legacy'},
 'user_args': ['python',
               'sweep_configs/orion_bug.py',
               '--b_optim.lr~loguniform(1e-6, 0.5, shape=4)']}
2022-01-25 15:19:45,436::DEBUG::orion.core.io.experiment_builder::    Branching config:
{}
2022-01-25 15:19:45,436::DEBUG::orion.core.io.experiment_builder::Merging user and db configs:
2022-01-25 15:19:45,436::DEBUG::orion.core.io.experiment_builder::    config from user:
{'debug': False,
 'metadata': {'VCS': {'HEAD_sha': 'e987e9272235cea57b8121412d0d25ae24075898',
                      'active_branch': 'numerical_experiments',
                      'diff_sha': '1e41bd0f60270609869157525ba045663ef27f7d7cedf30342b8322ff3d8225c',
                      'is_dirty': True,
                      'type': 'git'},
              'orion_version': '0.2.1',
              'parser': {'cmd_priors': [['/b_optim.lr',
                                         'loguniform(1e-6, 0.5, shape=4)']],
                         'config_file_data': {},
                         'config_prefix': 'config',
                         'converter': None,
                         'file_config_path': None,
                         'file_priors': [],
                         'parser': {'arguments': [['_pos_0', 'python'],
                                                  ['_pos_1',
                                                   '/home/fabrice/repos/scalingDTP/sweep_configs/orion_bug.py'],
                                                  ['b_optim.lr',
                                                   'orion~loguniform(1e-6, '
                                                   '0.5, shape=4)']],
                                    'keys': [['_pos_0', '_pos_0'],
                                             ['_pos_1', '_pos_1'],
                                             ['b_optim.lr', '--b_optim.lr']],
                                    'template': ['{_pos_0}',
                                                 '{_pos_1}',
                                                 '--b_optim.lr',
                                                 '{b_optim.lr}']}},
              'priors': {'/b_optim.lr': 'loguniform(1e-6, 0.5, shape=4)'},
              'user': 'fabrice',
              'user_args': ['python',
                            'sweep_configs/orion_bug.py',
                            '--b_optim.lr~loguniform(1e-6, 0.5, shape=4)'],
              'user_script': 'sweep_configs/orion_bug.py',
              'user_script_config': 'config'},
 'space': {'/b_optim.lr': 'loguniform(1e-6, 0.5, shape=4)'},
 'storage': {'database': {'host': '',
                          'name': 'orion',
                          'port': 27017,
                          'type': 'ephemeraldb'},
             'type': 'legacy'},
 'user_args': ['python',
               'sweep_configs/orion_bug.py',
               '--b_optim.lr~loguniform(1e-6, 0.5, shape=4)']}
2022-01-25 15:19:45,436::DEBUG::orion.core.io.experiment_builder::    config from DB:
{}
Traceback (most recent call last):
  File "/home/fabrice/miniconda3/envs/target_prop/bin/orion", line 8, in <module>
    sys.exit(main())
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/cli/__init__.py", line 37, in main
    return orion_parser.execute(argv)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/cli/base.py", line 89, in execute
    returncode = function(args)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/cli/hunt.py", line 198, in main
    experiment = experiment_builder.build_from_args(args)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 752, in build_from_args
    return build(**cmd_config)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 175, in build
    config = consolidate_config(name, version, config)
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 264, in consolidate_config
    resolve_config.update_metadata(config["metadata"])
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/resolve_config.py", line 303, in update_metadata
    cmdline_parser.set_state_dict(metadata["parser"])
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/orion_cmdline_parser.py", line 134, in set_state_dict
    self.infer_user_script(self.parser.format(self.parser.arguments))
  File "/home/fabrice/miniconda3/envs/target_prop/lib/python3.8/site-packages/orion/core/io/cmdline_parser.py", line 98, in format
    formatted.append(item.format(**configuration))
KeyError: 'b_optim'
```
