### ISSUE TITLE
Runner observe trials with result = None

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#819]
Bug report from @jbeirer

> When running experiments sequentially, I get the following error after a few experiments have been completed:
> 
> Traceback (most recent call last):
>   File "runOrionSingularity.py", line 484, in <module>
>     expManager.addExperiment(experiment, experimentName, kwargs)
>   File "runOrionSingularity.py", line 370, in addExperiment
>     if self._shouldRelease(): self.releaseExperiments()
>   File "runOrionSingularity.py", line 347, in releaseExperiments
>     experiment.workon(self.main, n_workers = self.nWorkers,  **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/orion/client/experiment.py", line 809, in workon
>     rval = runner.run()
>   File "/usr/local/lib/python3.8/site-packages/orion/client/runner.py", line 236, in run
>     gathered = self.gather()
>   File "/usr/local/lib/python3.8/site-packages/orion/client/runner.py", line 328, in gather
>     self.client.observe(trial, result.value)
>   File "/usr/local/lib/python3.8/site-packages/orion/client/experiment.py", line 620, in observe
>     trial.results += [Trial.Result(**result) for result in results]
> TypeError: 'NoneType' object is not iterable
> 
> The number of experiments after which this occurs seems to vary (I have observed a range between 1 - 6 completed experiments so far). After the error occurs, I need to re-submit the HTCondor jobs each time. At this point it is not really urgent for me, but eventually we will want to run Orion again in a few months time. Thanks!
> 
> The function only has one return statement and I never had these issues in prior versions:
> 
> return [
>         {"name": "meta_data", "type": "statistic", "value": meta_data}, 
>         {"name": "error",     "type": "objective", "value": error_rate}
> ]
> 
> This is only with 250 workers (and a single experiment). Let me know if I can help to track this down further.
> 
> I forgot to mention: 1000 trials :)

**Comment by bouthilx** [comment]
Assuming the function always returns None indeed, then it looks like it may be a synchronisation issue during gather. When calling this part:
```
File "/usr/local/lib/python3.8/site-packages/orion/client/runner.py", line 328, in gather
self.client.observe(trial, result.value)
```
the result.value should be a result otherwise we expect that the process failed and accessing `value` would raise locally the exception of the crashed worker. It does not seam to raise any exception, so I suspect that there might be a synchronisation issue with the dask backend, which is not assigning the result properly to the future.
